# yaml file configuration to deploy the containerized application
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-app
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flask-app
    spec:
      containers:
        - image: etamarah/__IMAGE_NAME__:__TAG__
          name: flask-app
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
